ARDUINO_DIR            = /usr/share/arduino
TARGET                 = WeatherDuino_lcd
ARDUINO_LIBS           = OneWire LiquidCrystal DHT DallasTemperature EEPROM
ARDUINO_SKETCHBOOK     = $(HOME)/sketchbook
MCU                    = atmega328p
F_CPU                  = 16000000
ARDUINO_PORT           = /dev/ttyUSB0
AVRDUDE_ARD_BAUDRATE   = 115200
AVRDUDE_ARD_PROGRAMMER = arduino

include $(ARDUINO_DIR)/Arduino.mk
